services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: 
      - ./backend/.env
    restart: unless-stopped
    volumes:
      - ./backend/products.json:/app/products.json:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/products || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
